### ISSUE TITLE
Selection turing off

### ISSUE THREAD

**Issue by hik200** [softark/yii2-dual-listbox#1]
![60dac06f98](https://cloud.githubusercontent.com/assets/19670639/18204050/454eafc2-7123-11e6-92bc-235f58e7965f.jpg)
![d53e0b19a6](https://cloud.githubusercontent.com/assets/19670639/18204051/454fa882-7123-11e6-93fb-a7f945a74b69.jpg)

when do via model, selection turning off!

**Comment by softark** [comment]
You don't need to set 'selection' when you are using model.
And, is your 'genre' attribute of the model an array? It should be.

**Comment by hik200** [comment]
how i can send result to the model without model?
(sorry i`m newbie)

**Comment by hik200** [comment]
i`m send via model but don`t know how to work without model.

**Comment by softark** [comment]
I hope the following article will help you understand how to construct a model for your scenario.

http://www.yiiframework.com/wiki/836/how-to-create-update-a-model-with-its-related-items-using-listbox-or-checkboxlist/

You can replace the listbox (or checkboxlist) in the article with dual listbox.
