### ISSUE TITLE
buttons are different

### ISSUE THREAD

**Issue by paskuale75** [softark/yii2-dual-listbox#5]
What class or style for the buttons ? the buttons are different from the [official page](https://www.virtuosoft.eu/code/bootstrap-duallistbox/)

thanks

**Comment by softark** [comment]
As you see in "composer.json", this extension is a thin wrapper of "istvan-ujjmeszaros/bootstrap-duallistbox ~3.0.6". So the class or style of the buttons depend on it, not on this extension.

**Comment by paskuale75** [comment]
after composer update I've this message:

> There's no fixed dependency configured.)
> istvan-ujjmeszaros/bootstrap-duallistbox suggests installing components/jquery (2.0.*)
> istvan-ujjmeszaros/bootstrap-duallistbox suggests installing twbs/bootstrap (3.*)


what does it mean ? tnx

**Comment by softark** [comment]
Those messages are from the composer.json of istval-ujimeszaros/bootstrap-duallistbox. It suggests you to use the specific versions of jquery and bootstrap.

As you see int the composer.json of this extension (I mean softark/yii2-dual-listbox),  it is only a thin wrapper of "istvan-ujjmeszaros/bootstrap-duallistbox". It doesn't say anything about jquery and bootstrap. So there's nothing it can do regarding the message.

Probably some of your other dependent libraries require higher versions of jquery and/or bootstrap. This might or might not be a serious problem to your project. I'm not for sure.
