### ISSUE TITLE
Dependency loading error when using bootstrap4

### ISSUE THREAD

**Issue by FreekGille** [softark/yii2-dual-listbox#6]
Hello!

I've been trying this extension but ran into some issues with the AppAsset loading. In `DualListBoxAsset.php` there are the following dependencies:
```php
public $depends = [
  'yii\web\JqueryAsset',
  'yii\bootstrap\BootstrapAsset',
];
```

I'm using Yii2 with Bootstrap4 which is referenced by `yii\bootstrap4\BootstrapAsset` so the above dependency fails for me. Replacing `bootstrap` with `bootstrap4` fixes the issue. Would it be possible to remove this dependency or support bootstrap4 as well?

**Comment by softark** [comment]
OK, I've dropped bootstrap3 dependence from this extension.
Now it should work with boostrap4 as well as bootstrap3.
